server:
  jetty:
    threads:
      #acceptors???????HTTP??
      acceptors: 4
      #selectors???????HTTP???
      selectors: 8
      #worker???????Web??
      min: 8
      max: 200
  port: 7700
  servlet:
    context-path: /his-api

spring:
  servlet:
    multipart:
      #??????
      enabled: true
      #??????????20M
      max-file-size: 20MB
      #HTTP??????20M
      max-request-size: 20MB
